# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fanqi/Documents/GitHub/Cache/Project/soc_axi_lite_loongson/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
# IP: The module: 'axi_crossbar_1x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fanqi/Documents/GitHub/Cache/Project/soc_axi_lite_loongson/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_1x2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/fanqi/Documents/GitHub/Cache/Project/soc_axi_lite_loongson/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2.xci
# IP: The module: 'axi_crossbar_1x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fanqi/Documents/GitHub/Cache/Project/soc_axi_lite_loongson/rtl/xilinx_ip/axi_crossbar_1x2/axi_crossbar_1x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_1x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
