# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fanqi/Documents/GitHub/Cache/Project/soc_axi_lite_loongson/rtl/xilinx_ip/unsigned_mult/unsigned_mult.xci
# IP: The module: 'unsigned_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fanqi/Documents/GitHub/Cache/Project/soc_axi_lite_loongson/rtl/xilinx_ip/unsigned_mult/unsigned_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unsigned_mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/fanqi/Documents/GitHub/Cache/Project/soc_axi_lite_loongson/rtl/xilinx_ip/unsigned_mult/unsigned_mult.xci
# IP: The module: 'unsigned_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fanqi/Documents/GitHub/Cache/Project/soc_axi_lite_loongson/rtl/xilinx_ip/unsigned_mult/unsigned_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unsigned_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
